# This Workflow announces a release in Eclipse Mattermost to https://mattermost.eclipse.org/eclipse/channels/eclipse-che-releases
name: Release - Send mattermost notification
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be announced. Should be in format 7.y.z'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Verify branches
      id: check
      run: |
        BRANCH=${{ github.event.inputs.version }}
        BRANCH=${BRANCH%.*}.x
        echo "::set-output name=branch-check::$(./utils/check-branches.sh ${BRANCH})"
    - name: Create success message
      run: |
        milestone=${{ github.event.inputs.version }}
        milestone=${milestone%.*}; echo "milestone: ${milestone}"
        echo "{\"text\":\":che-logo: Che ${{ github.event.inputs.version }} has been released.\n\n Please resolve or move unresolved issues assigned to this milestone: https://github.com/eclipse/che/milestones/${milestone}\"}" > mattermost.json
    - name: Create failure message
      if: ${{ failure() }}
      run: |
        echo "{\"text\":\":che-logo: Che ${{ github.event.inputs.version }} release final checks have failed:\n\n ${{join(steps.check.outputs.*, '\n')}}.\"}" > mattermost.json
    - name: Send message
      if: ${{ success() }} || ${{ failure() }}
      uses: mattermost/action-mattermost-notify@1.1.0
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: eclipse-che-releases
        MATTERMOST_USERNAME: che-bot
